---
###Title: "HW4"

###author: "anjal hussan"

###date: "10/14/2017"

###output: html_document
####4.4 Heights of adults.
Researchers studying anthropometry collected body girth measurements and skeletal diameter measurements, as well as age, weight, height and gender, for 507 physically active individuals. The histogram below shows the sample distribution of heights in centimeters.

Min 147.2 Q1 163.8 Median 170.3 Mean 171.1 SD 9.4 Q3 177.8 Max 198.1

(a) What is the point estimate for the average height of active individuals? What about the median?
Ans: point estimate for average height: 171.1 cm median: 170.3 cm

(b) What is the point estimate for the standard deviation of the heights of active individuals? What about the IQR?
Ans:
standard deviation: 9.4cm
IQR: 177.8cm − 163.8cm = 14cm

(c) Is a person who is 1m 80cm (180 cm) tall considered unusually tall? And is a person who is
1m 55cm (155cm) considered unusually short? Explain your reasoning.
Ans:
A person 180 cm tall would be on the first standard deviation from the mean
(171.1cm + 9.4cm = 180.5cm) which is slightly above average. The person 155 cm tall is more than one standard deviation, but less than two below the mean. This would make the person below average in height, but not unusually short

(d) The researchers take another random sample of physically active individuals. Would you expect the mean and the standard deviation of this new sample to be the ones given above? Explain your reasoning.
Ans: 
No a random sample will included many but not all individuals that were not in the first sample, the second sample will have a different mean and standard deviation than the first sample. We can expect that the second mean and standard deviation will be close to the first.

(e) The sample means obtained are point estimates for the mean height of all active individuals, if the sample of individuals is equivalent to a simple random sample. What measure do we use to quantify the variability of such an estimate (Hint: recall that SDx¯=σn√SDx¯=σn)? Compute this quantity using the data from the original sample under the condition that the data are a simple random sample.

Ans: standard error which is the standard deviation divided by the square root of the sample size( nn).
SDx¯=9.4cm507√=0.4174687cmSDx¯=9.4cm507=0.4174687cm

####4.14 Thanksgiving spending, Part I.
The 2009 holiday retail season, which kicked off on November 27, 2009 (the day after Thanksgiving), had been marked by somewhat lower self-reported consumer spending than was seen during the comparable period in 2008. To get an estimate of consumer spending, 436 randomly sampled American adults were surveyed. Daily consumer spending for the six-day period after Thanksgiving, spanning the Black Friday weekend and Cyber Monday, averaged $84.71. A 95% confidence interval based on this sample is ($80.31,$89.11).

Determine whether the following statements are true or false, and explain your reasoning.

(a) We are 95% confident that the average spending of these 436 American adults is between $80.31 and $89.11.
Ans:
False, we are 95% confident that the mean spending for the entire population between $80.31 and $89.11

(b) This confidence interval is not valid since the distribution of spending in the sample is right skewed.
Ans:
False, the validity of the confidence interval is based on the sample mean being Normally Distributed, not the sample itself. Since these people were selected at random and the sample size is greater than 30, by the Central Limit Theorem, the sample mean is normally distributed and the confidence intervals are valid.

(c) 95% of random samples have a sample mean between$80.31 and $89.11.
ans: 
False, 95% of random samples produced confidence intervals that captures the population mean.

(d) We are 95% confident that the average spending of all American adults is between $80.31 and $89.11.
Ans: True

(e) A 90% confidence interval would be narrower than the 95% confidence interval since we don’t need to be as sure about our estimate.
Ans: True

(f) In order to decrease the margin of error of a 95% confidence interval to a third of what it is now, we would need to use a sample 3 times larger.
Ans: False, margin of error is z∗xSEz∗xSE, and SE goes as the inverse square root of sample. To decrease margin of error by 3 we need to increase sample size by 9 because 13=19√13=19.

(g) The margin of error is 4.4.
ans: True, Margin of error is z∗xSEz∗xSE, which is 1/2 the confidence interval so, $89.11−$80.312=$4.4

####4.24 Gifted children, Part I.
Researchers investigating characteristics of gifted children collected data from schools in a large city on a random sample of thirty-six children who were identified as gifted children soon after they reached the age of four. The following histogram shows the distribution of the ages (in months) at which these children first counted to 10 successfully. Also provided are some sample statistics.

n = 36, min = 21, mean = 30.69, sd = 4.31, max = 39

Question: Are conditions for inference satisfied?
Ans: Yes, the children were randomly selected, independent of each other, and the sample size is greater than 30.

4.26 Gifted children, Part II.
Exercise 4.24 describes a study on gifted children. In this study, along with variables on the children, the researchers also collected data on the mother’s and father’s IQ of the 36 randomly sampled gifted children. The histogram below shows the distribution of mother’s IQ. Also provided are some sample statistics. n 36 min 101 mean 118.2 sd 6.5 max 131

(a) Perform a hypothesis test to evaluate if these data provide convincing evidence that the average IQ of mothers of gifted children is different than the average IQ for the population at large, which is 100. Use a significance level of 0.10.

z <- (118.2-100)/(6.5/6)
p <- 2*pnorm(-abs(z))
p is 2.44044e-63
p is much lower than 0.1 so we can reject the null hypothesis that the sample mean IQ is the same as the population mean IQ of 100 and take the alternative hypothesis that the sample mean IQ is different from the population mean IQ.

(b) Calculate a 90% confidence interval for the average IQ of mothers of gifted children.
```{R}
lower_vector <- 118.2 - 1.645*(6.5/6)
upper_vector <- 118.2 + 1.645*(6.5/6)
c(lower_vector, upper_vector)

```

##[1] 116.4179 119.9821


(c) Do your results from the hypothesis test and the confidence interval agree? Explain.

As the confidence interval does not contain the population mean IQ of 100 it is consistent with the hypothesis test.

####4.34 CLT. 
Define the term “sampling distribution” of the mean, and describe how the shape, center, and spread of the sampling distribution of the mean change as sample size increases.

Ans: 
The means sampling distribution of the mean is the distribution of the mean from many different samples from a population. As the sample size increases the sampling distribution becomes closer to the Normal Distribution in its shape. The center does not change much and approaches the population mean. The spread narrows as sample size increases.

####4.40 CFLBs.
A manufacturer of compact fluorescent light bulbs advertises that the distribution of the lifespans of these light bulbs is nearly normal with a mean of 9,000 hours and a standard deviation of 1,000 hours.

(a)
What is the probability that a randomly chosen light bulb lasts more than 10,500 hours?

Z <- (10500-9000)/1000
1 - pnorm(Z)
## [1] 0.0668072

A 6.68% chance that a single bulb will last 10,500 hours.

(c) What is the probability that the mean lifespan of 15 randomly chosen light bulbs is more than 10,500 hours?

Z <- (10500-9000)/(1000/15^0.5)
1 - pnorm(Z)

## [1] 3.133452e-09

####4.48 Same observation, different sample size.
Suppose you conduct a hypothesis test based on a sample where the sample size is n= 50, and arrive at a p-value of 0.08. You then refer back to your notes and discover that you made a careless mistake, the sample size should have been n = 500. Will your p-value increase, decrease, or stay the same? Explain.

p-value is derived from the Z-score using SE. Everything else being the same, as sample size increased, SE decreases and Z-score increases, hence, so p-value decreases.
