---
title: "HW2"
author: "anjal hussan"
date: "9/13/2017"
output: html_document
---
####Problem 2.6
If you roll a pair of fair dice, what is the probability of - 
a. Getting a sum of 1?
P(1) = 0, because the minimum sum is 2, one on each die.

b. Getting a sum of 5?
there are two ways to get 1 and 4, two ways to get 2 and 3 any roll. With a 5 or 6 will not result in a total of 5.
Hence P(5) = 4/36 = 1/9;

c. Getting a sum of 12?
The only way to get a 12 is to get two sixes in two dice
Hence P(12) = 1/36; 

***

####Problem 2.8
The American Community Survey is an ongoing survey that provides data every year to give communities the current information they need to plan investments and services. The 2010 American Community Survey estimates that 14.6% of Americans live below the poverty line, 20.7% speak a language other than English (foreign language) at home, and 4.2% fall into both categories.

A. Are living below the poverty line and speaking a foreign language at home disjoint?
Ans:
Disjoint is a term meaning mutually exclusive. Since 4.2% fall into both categories, being below the poverty line and speaking a foreign language at home are not Disjoint

B. Draw a Venn diagram summarizing the variables and their associated probabilities.
Ans:
```{R vennDiagram}
#install.packages('VennDiagram')
library(VennDiagram)
draw.pairwise.venn(area1 = 0.146, area2 = 0.207, cross.area = 0.042, category = c("Below Poverty Line", "Foreign Language Speaker"), fill = c("blue","pink"), alpha = rep(0.5, 2), cat.pos = c(0,0), cat.dist = rep(0.025 ,2))
```

C. What percent of Americans live below the poverty line and only speak English at home?
Ans: 
Live below the poverty level and Speak Only English = live below poverty level - both categories
14.6% - 4.2% = 10.4 %

D. What percent of Americans live below the poverty line or speak a foreign language at home?
Addition rule P(A or B) = P(A) + P(B) - P(A and B) 
0.207 + 0.146 - 0.042 
= 0.207 + 0.146 - 0.042 
= 0.311 or 31.1%

E. What percent of Americans live above the poverty line and only speak English at home?
Percent living only Below poverty line = 14.6 - 4.2 = 10.4
Percent speak a foreign language regardless of poverty line =  20.7-4.2 = 16.5
Percent living Above the poverty line and Speak only english = 
100 - (10.4+16.5+4.2) = 68.9
Ans is 68.9 percent

D. Living below poverty and speaking a foreign language at home are independent events. On doesn't have direct influence to others'

***

####Problem 2.20
Assortative mating is a nonrandom mating pattern where individuals with similar genotypes and/or phenotypes mate with one another more frequently than what would be expected under a random mating pattern. Researchers studying this topic collected data on eye colors of 204 Scandinavian men and their female partners. The table below summarizes the results. For simplicity, we only include heterosexual relationships in this exercise.

A. What is the probability that a randomly chosen male respondent or his partner has blue eyes?
Probability of having blue eyed female = 108/204 = 0.5294118
Probability of having blue eyed male = 114/204 = 0.5588235
Probablility of having blue eyed both male and female = 78/204 = 0.3823529
Hence: Probability of a randomly chosen male respondent or his partner has blue eyes is:
(0.5294118 + 0.5588235) - 0.3823529
ans: 0.7058824

B. What is the probability that a randomly chosen male respondent with blue eyes has a partner with blue eyes?
78/204 = 0.3823529

C. What is the probability that a randomly chosen male respondent with brown eyes has a partner with blue eyes? 
19/204 = 0.09313725

D. What about the probability of a randomly chosen male respondent with green eyes having a partner with blue eyes?
11/204 = 0.05392157

E. Does it appear that the eye colors of male respondents and their partners are independent? Explain your reasoning.

Probability of having Blue eye of male has no influence to the possible outcome of their partner's eye color. Hence - eye colors of male respondents and their partners are independent.

***

####Problem 2.30
The table below shows the distribution of books on a bookcase based on whether they are nonfiction or fiction and hardcover or paperback.

A. Find the probability of drawing a hardcover book first then a paperback fiction book second when drawing without replacement.

P=(28/95)∗(59/94)=0.1849944

B. Determine the probability of drawing a fiction book first and then a hardcover book second, when drawing without replacement.
Ans:
Since you can have a hardcover fiction book we need to find the probablity of hardcover given fiction.
13/72 = 0.1805556

an 18.0555% chance that first fiction book will be hard cover
P=(72/95)∗(27/94)=0.2176932

we have an 1-0.1805556 = 0.8194444 chance that First fiction book will not be hard cover
P=(72/95)∗(28/94)=0.2257559

probability of drawing a fiction book first and then a hardcover book second without replacement is :
P= (0.819445 * 0.2257559) + (0.180555 * 0.2176932) =0.2243001

C. Calculate the probability of the scenario in part (b), except this time complete the calculations under the scenario where the first book is placed back on the bookcase before randomly drawing the second book.
Ans:
Since the second book is placed back on the self, it no longer affects the second draw, and all books are available to draw.
P=(72/95)x(28/95)=0.2233795

D.The final answers to parts (b) and (c) are very similar. Explain why this is the case.
Ans:
Dividing by 95 will result in a smaller number than dividing by 94. Scenerio (c) will have a smaller probabilty than (b), however in scenerio (b) we have to factor in the slighty lower probablity event that the first book was both hardcover and fiction. That reduces the overall probabilty of (b) and by coincidence makes it similar to (C).

***
 
####Problem 2.38
An airline charges the following baggage fees:$25 for the first bag and $35 for the second. Suppose 54% of passengers have no checked luggage, 34% have one piece of checked luggage and 12% have two pieces. We suppose a negligible portion of people check more than two bags.

A. Build a probability model, compute the average revenue per passenger, and compute the corresponding standard deviation.
Ans:
```{R BAGS}
bags <- matrix(c(0.54,0.34,0.12), nrow = 1, ncol = 3)
rownames(bags) <- c("Probabilty")
colnames(bags) <- c("$0", "1bag=$25", "2bag=$35")
bags
```

per passenger:
0∗0.54+25∗0.34+35∗0.12=12.7

Var(X)=(0−12.7)2∗0.54+(25−12.7)2∗0.34+(35−12.7)2∗0.12=198.21

SD(X)=√=198.21 =14.07871

B. About how much revenue should the airline expect for a flight of 120 passengers? With what standard deviation? Note any assumptions you make and if you think they are justified.
Ans:
Total Revenue with 120 Passengers:
120∗E(X)=120∗12.7=1524

$1524 for a flight of 120 passengers on average.
120∗SD(X)=120∗14.07871=1689.445

***

####Problem 2.44
The relative frequency table below displays the distribution of annual total personal income (in 2009 inflation-adjusted dollars) for a representative sample of 96,420,486 Americans. These data come from the American Community Survey for 2005-2009. This sample is comprised of 59% males and 41% females.

A. Describe the distribution of total personal income.
Ans: 
```{R income}
income <- c(0.022,0.047,0.158,0.183,0.212,0.139,0.058,0.084,0.097)
barplot(income)
```


B. What is the probability that a randomly chosen US resident makes less than $50,000 per year?
Ans:
P=0.022+0.047+0.158+0.183+0.212=0.622

C. What is the probability that a randomly chosen US resident makes less than $50,000 per year and is female? 
Ans: 
P=0.622∗0.41=0.25502

***

End of this file